= FIN 300

== Study Guide
* the test is mainly on Week 5

=== Chapter One


.*The role of the financial manager:*
* as a fin manager you want to make decisions that create value in particular *long term value*
* fin mgrs face what is called the *Agency Problem*
** this mean that when they are taking into consideration all of the stakeholders and how an outcome will affect them sometimes they may have a conflict of interest that they have to deal with.
* goal is to select assets that will generate the greatest *CASH FLOWS* for the owners of the company.
* fin mgrs use *CAPITAL BUDGETING* when deciding what assets to purchase
* they also deal with the day 2 day ops of the company, falls under the *WORKING CAPITAL MANAGEMENT* 
** Working capital management is a business strategy designed to ensure that a company operates efficiently by monitoring and using its current assets and liabilities to their most effective use.
* maximize the value of the firms stock
* *Goals of a financial manager:*
** Survive
** Avoid Bankruptcy
** Avoid Financial Distress
** Beat the Competiton
** Maximize Sales/Market Share
** Minimize Costs
** Maximize Profits 
** Maintain Steady Earnings Growth
* *Decisions for Financial Managers of Companies:*
** Expand or not?
** Increase or Keep Low Risk?
** Strive for Market Share or Maintain (how aggressive?)
** Borrow Money to Fund Growth?
** How well do you want to sleep at night?
* there are some factors that are outside of the control of fin mgrs that do affect the stock price (econ shocks, legislation, state of econ, stock market conditions, and now pandemics)
* *Major factors that managers can affect*
** The Firm
** Expected Cash Flow
* Warren Buffet says to invest in companies with strong leadership that has integrity, honesty, intelligence and energy
* *How do we get financial managers to be better aligned with the goals of shareholders?*
** BOD: (*Board of Directors*)
*** many boards have been under fire for the past 10 yrs or so 
** Align Compensation with the performance of the stock
** Hire managers with integrity
** Activist Investors 
*** Publishing managers performance publically to allow active investors 
** Threat of take over


.*Stakeholder Theory:*
* *Stakeholder Theory* - this is a view of capitalismn that stresses the interconnected relationships between a business and its customers, suppliersk, employees, investors, communities and others who have a stake in the organization  


* *Stakeholder Types Examples:*
** 1. Shareholders 
** 2. Employees
** 3. Clients/Customers
** 4. Suppliers
** 5. The Community
** 6. Government
** 7. Creditors
** 8. Managers
** 9. Regulators
** 10. Competitors
** 11. The Environment
** 12. Social Media
* Stakeholders will generally have different interest and goals than the owners of the company
** this leads to financial managers having an *AGENCY PROBLEM*


.*Capital budgeting and financing decisions:* 
* *Capital Budgeting* - it is the decision making proccess through which financial managers use to make decisions about which productive assets to aquire
** a company might assess a prospective project's lifetime cash inflows and outflows to determine whether the potential returns that would be generated meet a sufficient target benchmark. The capital budgeting process is also known as investment appraisal
* *Financing Decisions* - determining how a firm should finance or pay for the assets that are being evaluated. 
** There are generally two basic ways for the firm to pay for these productive assets:  
*** 1.  *Equity* (i.e. Issuance of stock…….stockholders OWN the company)
*** 2.  *Debt* (i.e. Issuance of bonds…….bondholders are creditors of the company)


.*Goal of the firm:*
* The goal of the firm should be to maximize the stock value of the firm


.*Agency Conflicts/Relationships:*
* when they are taking into consideration all of the stakeholders and how an outcome will affect them sometimes they may have a conflict of interest that they have to deal with.
* When talking about Agency conflicts there are two key figures
** *Principle* - the entity that hires the *agents* that do work on behalf of the *principle* Ex. a company 
** *Agents* - the entity that is hired by the *principle* entity in order to carry out work on behalf of that entity. Managers are legally considered *agents* and have the obligation to put the shareholders(*principle*) above their own. *agents* are the ones who have the duty to report to principles if they have a conflict of interest 
* These conflicts specifically are called *agency conflicts*


.*Alignment of goals of shareholders to managers*:
* *How do we get financial managers to be better aligned with the goals of shareholders?*
** BOD: (*Board of Directors*)
*** many boards have been under fire for the past 10 yrs or so 
** Align Compensation with the performance of the stock
** Hire managers with integrity
** Activist Investors 
*** Publishing managers performance publically to allow active investors 
** Threat of take over


.*Sarbanes Oxley*:
* The Sarbanes-Oxley Act of 2002 (aka SOX Act)
** by U.S. Congress to help protect investors from fraudulent reporting by corporations
** mandated strict reforms on the current regulations at the time and imposed very big fines for people who were to break these laws in the future.

=== Chapter Two

.*FED - goals and tools*: 
* *Five major goals of the FED*
** *Price Stability*
*** since 1970s efforts to control inflation has been a major goal and effort of the FED. The FED has an inflation goal of *2%*. Currently it is running at a rate of 9% and the way to slow demand is to raise the interest rates and to decrease the amount of money is in the market in order to strangle demand. That is what Powell (*Chair of the Federal Reserve*) is currently doing.
** *Full employment*
*** the fed considers 4% unemployment to classify whether or not the country is fully employed, they aim for a rate between 4% - 6% (now sitting a 3.6%)
** *Sustained Economic Growth*
*** then fed would like the GDP (gross domestic product) to be within the range of 2% - 3%, currently it is sitting at 3.5% but this is expected to drop through this year
** *Having Better Payment Stability v. Foreign Entities*
** Protect the value of the dollar (MORAL SUASION)
*** *Moral Suasion* - the use of non physical/overty coercion means such as rhetorical appeals, persuasion or explicit threats in order to pursuade someone
* what the FED says about the present and the future carries a lot of weight.  There are so called FED WATCHERS who work at Wall Street banks that their job is to interrupt what the FED is saying.
* Many of the FED's policies are conflicting. 
* *Tools used by the FED:*
** *Discount Rate* - this is the rate charged by banks who borrow short term money from the FED it is currently 1.75% One year ago, it was .25%
*** *why borrow?* banks so often borrow from the FED in order to maintain their prescribed reserve requiremnents 
** *FED Open Market operations*
*** this has become the most important tool in the FED's *tool box*
*** *REPOS* - repurchase agreement that is a short term loan to *primary dealers* that are generally short term in nature.
**** *Primary Dealers* - banks or brokers that are sanctioned to trade US gov securities
** *Reserve Requirements* - a % of money deposited into a bank that a bank has to hold in order to make sure in the case of mass quick withdrawls that they can cover their liabilities
* *Exchange Rates*
* *Moral Suassion*
* *FEDS FUND RATE* - this is the target interest rate set by the Federal Open Market Committee (FOMC), it is the rat eat which commercial banks borrow and lend their excess reserves to each other overnight
** *FOMC* - meets 8 times a year to set the targe tfederal funds rate which is par tof its monetary policy, and used to promote econ growth, from 2008 - 2016 the *FED FUINDS* rate was vitually 0
** currentrange is 1.5% - 1.75%

.*Financial Markets*:
* a mechanism for which people with excess money invest/lend money to people/business in need of capital
** The US financial system is considered to be the most efficient in the world
** funds can flow *directly* thru the financial markets and *indirectly* through financial institutions

.*Primary v. Secondary Markets*: 
* *Primary Dealers* - banks or brokers that are sanctioned to trade US gov securities they are the first ones to own securites issued by the fed
* *Secondary Dealers* - investors who buy and sell securities on exchanges and do not directly interact with the fed

.EMH:
* the *EFFICIENT MARKET HYOPTHESIS*, It argues tha tall information which goes into the pricing of financial instruments is readily availible to all borrowers and lenders at a negligible cost. Basically all investors are looking at the same information and that there should be no excessive returns.
** Both Kendell (1950’s) and Malkeil (Princeton) have done work on EMH stating that price changes should be random and unpredictable  and that prices of assets follow a RANDOM WALK.  They state that the markets are not irrational (this is highly debatable).   Malkeil has acknowledged that NEWS interpretation sets new recurring equilibriums in the marketplace

.Real v. Nominal Interest Rates:
* 

.Basics of the Fisher Equation:
* 

=== Chapter Three

.Annual report:  balance sheet, income statement and RE statement: 
* 

.Statement of Cashflows:
* 

.Current Assets and Liabilities: 
* 

.Net Working Capital:
* 

.Equity:
* 

.What is treasury stock:
* 

.Market Value v. Book Value:
* 

.Basics of impact of taxes on Corporations:
* 

=== Chapter Four

.Financial ratios, performance, and interpretation of ratios: 
* 

.ROE, current ratio, quick ratio, inventory turnover, total asset turnover, debt ratios, equity multiplier, profit margins, ROA, EPS, PE, market to book, Dupont formula, enterprise value:
* 

.Trend Analysis: 
* 

.Peer Analysis:
* 

=== Chapter Five

.TVM
* 

.Future Value, and how to compute it:
*

.Present Value, and how to compute it:
*

.Compounding
* 

.Continuous Compounding
* 

.Discounting
*

=== Chapter Six

.Cash flows over time
* 

.PV of multiple cash flows
*

.Annuities (ordinary and annuity due)
* 

.PV of an annuity
*

.Amortization
*

.FV of an annuity
* 

.Basics of Perpetuity
* 

.Preferred Stock Dividends
*

.EAR/APR
* 
